Repository mju-likelion/12th-crossover-server-3, pull requests merged in 2024-06, with the labels that each got.

#2 Feature/#1 spring-init
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/airplaneletter/AirplaneLetterApplication.java
  src/test/java/com/example/airplaneletter/AirplaneLetterApplicationTests.java
Labels: good first issue

#4 Feature/#3 ERD 추가
  build.gradle
  src/main/java/model/BaseEntity.java
  src/main/java/model/Comment.java
  src/main/java/model/Post.java
  src/main/java/model/Term.java
  src/main/java/model/TermUser.java
  src/main/java/model/User.java
Labels: good first issue

#12 Feature/#12 add Authcontroller
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/dto/Dto.java
  src/main/java/com/example/airplaneletter/model/BaseEntity.java
  src/main/java/com/example/airplaneletter/model/Comment.java
  src/main/java/com/example/airplaneletter/model/Post.java
  src/main/java/com/example/airplaneletter/model/Term.java
  src/main/java/com/example/airplaneletter/model/TermUser.java
  src/main/java/com/example/airplaneletter/model/User.java
  src/main/java/com/example/airplaneletter/response/Response.java
Labels: enhancement

#11 Feature/#10 fix field naming
  src/main/java/com/example/airplaneletter/model/BaseEntity.java
  src/main/java/com/example/airplaneletter/model/Comment.java
  src/main/java/com/example/airplaneletter/model/Post.java
  src/main/java/com/example/airplaneletter/model/Term.java
  src/main/java/com/example/airplaneletter/model/TermUser.java
  src/main/java/com/example/airplaneletter/model/User.java
Labels: bug

#13 Feature/#9 add user api
  build.gradle
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/dto/LoginDto.java
  src/main/java/com/example/airplaneletter/repository/UserRepository.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: enhancement

#17 Feature/#15 add authentication, token, interceptor
  src/main/java/com/example/airplaneletter/AirplaneLetterApplication.java
  src/main/java/com/example/airplaneletter/authentication/AuthenticationConfig.java
  src/main/java/com/example/airplaneletter/authentication/AuthenticationContext.java
  src/main/java/com/example/airplaneletter/authentication/AuthenticationExtractor.java
  src/main/java/com/example/airplaneletter/authentication/PasswordHashEncryption.java
  src/main/java/com/example/airplaneletter/authentication/interceptor/AuthenticationInterceptor.java
  src/main/java/com/example/airplaneletter/authentication/token/JwtEncoder.java
  src/main/java/com/example/airplaneletter/authentication/token/JwtTokenProvider.java
  src/main/java/com/example/airplaneletter/authentication/user/AuthenticatedUser.java
  src/main/java/com/example/airplaneletter/authentication/user/AuthenticatedUserArgumentResolver.java
Labels: enhancement

#16 Feature/#6 PostApi 개발
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/dto/PostDto.java
  src/main/java/com/example/airplaneletter/dto/ResponseDto.java
  src/main/java/com/example/airplaneletter/repository/PostRepository.java
  src/main/java/com/example/airplaneletter/response/AllPostsResponseData.java
  src/main/java/com/example/airplaneletter/response/DetailedPostResponseData.java
  src/main/java/com/example/airplaneletter/service/PostService.java
Labels: enhancement

#19 Feature/#18 update AuthController
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/dto/CreateUserDto.java
  src/main/java/com/example/airplaneletter/dto/Dto.java
  src/main/java/com/example/airplaneletter/repository/UserRepository.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: enhancement

#23 Feature/#22 post api 수정
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/service/PostService.java
Labels: bug

#25 Feature/#24 add comment api
  Dockerfile
  src/main/java/com/example/airplaneletter/controller/CommentController.java
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/dto/CreateCommentDto.java
  src/main/java/com/example/airplaneletter/model/Post.java
  src/main/java/com/example/airplaneletter/repository/CommentRepository.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
  src/test/java/com/example/airplaneletter/AirplaneLetterApplicationTests.java
Labels: enhancement

#21 Feature/#20 exception 및 error 관련 개발
  src/main/java/com/example/airplaneletter/controller/ExceptionController.java
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/dto/ErrorResponseDto.java
  src/main/java/com/example/airplaneletter/errorCode/ErrorCode.java
  src/main/java/com/example/airplaneletter/exception/CustomException.java
  src/main/java/com/example/airplaneletter/exception/DtoValidationException.java
  src/main/java/com/example/airplaneletter/exception/NotFoundException.java
  src/main/java/com/example/airplaneletter/exception/UnauthorizedException.java
  src/main/java/com/example/airplaneletter/service/PostService.java
Labels: enhancement

#28 Feature/#26 controller에서 responseData 반환
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/controller/CommentController.java
Labels: enhancement

#31 Feature/#27 get all comments
  src/main/java/com/example/airplaneletter/controller/CommentController.java
  src/main/java/com/example/airplaneletter/dto/CommentData.java
  src/main/java/com/example/airplaneletter/model/Term.java
  src/main/java/com/example/airplaneletter/repository/CommentRepository.java
  src/main/java/com/example/airplaneletter/response/AllCommentsResponseData.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
Labels: enhancement

#33 Feature/#32 term api 개발
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/controller/TermController.java
  src/main/java/com/example/airplaneletter/dto/CreateTermDto.java
  src/main/java/com/example/airplaneletter/dto/CreateUserDto.java
  src/main/java/com/example/airplaneletter/dto/TermDto.java
  src/main/java/com/example/airplaneletter/model/Term.java
  src/main/java/com/example/airplaneletter/model/TermUser.java
  src/main/java/com/example/airplaneletter/repository/TermRepository.java
  src/main/java/com/example/airplaneletter/repository/TermUserRepository.java
  src/main/java/com/example/airplaneletter/response/AllTermsResponseData.java
  src/main/java/com/example/airplaneletter/response/TermResponseData.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
  src/main/java/com/example/airplaneletter/service/PostService.java
  src/main/java/com/example/airplaneletter/service/TermService.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: enhancement, good first issue

#36 Feature/#35 회원가입시 이메일 중복 검사 추가 및 패키지 명과 파일 위치 변경
  src/main/java/com/example/airplaneletter/authentication/interceptor/AuthenticationInterceptor.java
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/controller/CommentController.java
  src/main/java/com/example/airplaneletter/controller/ExceptionController.java
  src/main/java/com/example/airplaneletter/controller/PostController.java
  src/main/java/com/example/airplaneletter/controller/TermController.java
  src/main/java/com/example/airplaneletter/dto/comment/CreateCommentDto.java
  src/main/java/com/example/airplaneletter/dto/error/ErrorResponseDto.java
  src/main/java/com/example/airplaneletter/dto/login/LoginDto.java
  src/main/java/com/example/airplaneletter/dto/post/CreatePostDto.java
  src/main/java/com/example/airplaneletter/dto/response/Response.java
  src/main/java/com/example/airplaneletter/dto/response/comment/CommentListResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/comment/CommentResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/post/PostResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/post/PostWithCommentResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/term/TermListResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/term/TermResponseData.java
  src/main/java/com/example/airplaneletter/dto/term/CreateTermDto.java
  src/main/java/com/example/airplaneletter/dto/term/TermDto.java
  src/main/java/com/example/airplaneletter/dto/user/CreateUserDto.java
  src/main/java/com/example/airplaneletter/exception/ConflictException.java
  src/main/java/com/example/airplaneletter/response/Response.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
  src/main/java/com/example/airplaneletter/service/PostService.java
  src/main/java/com/example/airplaneletter/service/TermService.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: enhancement

#38 Feature/#37 nickname validation 수정
  src/main/java/com/example/airplaneletter/dto/user/CreateUserDto.java
Labels: enhancement

#39 Feature/#34 add exception
  src/main/java/com/example/airplaneletter/dto/response/comment/CommentResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/post/PostResponseData.java
  src/main/java/com/example/airplaneletter/dto/response/post/PostWithCommentResponseData.java
  src/main/java/com/example/airplaneletter/exception/ConflictException.java
  src/main/java/com/example/airplaneletter/exception/ForbiddenException.java
  src/main/java/com/example/airplaneletter/service/PostService.java
  src/main/java/com/example/airplaneletter/service/TermService.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: bug, enhancement

#41 Feature/#40 get comments
  src/main/java/com/example/airplaneletter/controller/CommentController.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
Labels: bug, enhancement

#43 Feature/#42 HealthController 추가
  src/main/java/com/example/airplaneletter/authentication/AuthenticationConfig.java
  src/main/java/com/example/airplaneletter/controller/HealthController.java
Labels: enhancement

#50 Feature/#49 modify errorcode
  src/main/java/com/example/airplaneletter/errorCode/ErrorCode.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
  src/main/java/com/example/airplaneletter/service/PostService.java
Labels: bug

#52 Feature/refactoring #51
  src/main/java/com/example/airplaneletter/authentication/AuthenticationExtractor.java
  src/main/java/com/example/airplaneletter/authentication/interceptor/AuthenticationInterceptor.java
  src/main/java/com/example/airplaneletter/authentication/user/AuthenticatedUserArgumentResolver.java
  src/main/java/com/example/airplaneletter/controller/AuthController.java
  src/main/java/com/example/airplaneletter/controller/TermController.java
  src/main/java/com/example/airplaneletter/dto/term/AgreeToTermDto.java
  src/main/java/com/example/airplaneletter/dto/user/CreateUserDto.java
  src/main/java/com/example/airplaneletter/errorCode/ErrorCode.java
  src/main/java/com/example/airplaneletter/service/CommentService.java
  src/main/java/com/example/airplaneletter/service/PostService.java
  src/main/java/com/example/airplaneletter/service/TermService.java
  src/main/java/com/example/airplaneletter/service/UserService.java
Labels: enhancement
